### ISSUE TITLE
Memory error

### ISSUE THREAD

**Issue by djolereject** [ankane/xgboost-ruby#7]
When I try to instantiate matrix via `XGBoost::DMatrix.new(x_train, label: y_train)` I sometimes get this error:
`IndexError (Memory access offset=0 size=13288 is out of bounds):`

Repeated commands sometimes make it just go through and sometimes it get stuck on this error for a while. Why is this happening and what could I do to prevent it?
Thanks.

**Comment by ankane** [comment]
Hi @djolereject, can you paste the stack trace?

**Comment by djolereject** [comment]
Hi @ankane, thanks for helping. Unfortunately there is not much to add to it, in the stack trace I only get a list of my methods:
```
web_1        | [9b4742b2-5b16-4cb3-8b29-05a401ecbe11] IndexError (Memory access offset=0 size=13264 is out of bounds):
web_1        | [9b4742b2-5b16-4cb3-8b29-05a401ecbe11]   
web_1        | [9b4742b2-5b16-4cb3-8b29-05a401ecbe11] lib/oracle/decision_tree.rb:47:in `new'
web_1        | [9b4742b2-5b16-4cb3-8b29-05a401ecbe11] lib/oracle/decision_tree.rb:47:in `create_matrices'
web_1        | [9b4742b2-5b16-4cb3-8b29-05a401ecbe11] lib/oracle/decision_tree.rb:57:in `train'
web_1        | [9b4742b2-5b16-4cb3-8b29-05a401ecbe11] lib/oracle/decision_tree.rb:17:in `initialize'
```

Those methods look like this:

```
    def train(model, num_rounds)
      train_matrix, test_matrix = create_matrices(model)
      params = { 'booster' => 'gbtree',
                 'objective' => 'multi:softprob',
                 'num_class' => 3,
                 'eval_metric' => 'merror',
                 'num_parallel_tree' => 10,
                 'seed' => 42 }
      @booster = XGBoost.train(params, train_matrix, num_boost_round: num_rounds,
                                                     evals: [[train_matrix, 'train'], [test_matrix, 'test']],
                                                     early_stopping_rounds: 10)
    end

    def create_matrices(model)
      split_index = (model.size * 0.8).to_i
      training_data = model[0...split_index]
      testing_data = model[split_index..]

      x_train = extract_sample(training_data, 0)
      y_train = extract_sample(training_data, 1)
      x_test = extract_sample(testing_data, 0)
      y_test = extract_sample(testing_data, 1)

      train_matrix = XGBoost::DMatrix.new(x_train, label: y_train)
      test_matrix = XGBoost::DMatrix.new(x_test, label: y_test)
      [train_matrix, test_matrix]
    end

    def extract_sample(from, at)
      from.map { |data| data[at] }
    end
```

So, it's only this oneliner of an error which actually looks like it's coming from C. Maybe somebody can notice some issue with this code that is obvious, because I'm seasoned rubist, but a beginner in this field.

**Comment by djolereject** [comment]
Just to add - same thing sometimes happen on Mac and on Linux Alpine docker container.

**Comment by ankane** [comment]
I was able to reproduce by passing an invalid matrix. Improved the error message in the commit above.

**Comment by djolereject** [comment]
Thanks!
